version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - bf:51:12:f0:cd:ce:de:ff:d6:be:a9:57:38:46:f2:b5
            - 52:98:bc:12:a7:7b:36:5b:68:09:1c:1c:4f:c0:51:31
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=tarea7-sa' >> $BASH_ENV
            virtualenv helloworld
            . helloworld/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Correr pruebas
          command: |
            . helloworld/bin/activate
            python test_hello_world.py
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            . helloworld/bin/activate
            pyinstaller -F hello_world.py
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to GCP via docker
          command: |
            ssh -i ~/.ssh/id_rsa_5298bc12a77b365b68091c1c4fc05131 -o StrictHostKeyChecking=no a.ricardoguzman@35.192.155.141 "/bin/bash ./deploy_app.sh $DOCKER_LOGIN/$IMAGE_NAME:$TAG"
